library(jsonlite)
data <- fromJSON("data/report.json")
#print(data)
data1 <- subset.data.frame(data, !is.na(data$imei), select = c('imei', 'XPO', "VZW", "OE", "FD"))
total <- nrow(subset.data.frame(data, !is.na(data$imei)))
print(sprintf("VZW vs XPO: %.1f %%", 100 * nrow(subset.data.frame(data, data$XPO == data$VZW)) / total))
print(sprintf("FD vs VZW: %.1f %%", 100 * nrow(subset.data.frame(data, data$FD == data$VZW)) / total))
print(sprintf("FD vs XPO: %.1f %%", 100 * nrow(subset.data.frame(data, data$FD == data$XPO)) / total))
print(sprintf("OE vs VZW: %.1f %%", 100 * nrow(subset.data.frame(data, data$OE == data$VZW)) / total))
print(sprintf("OE vs XPO: %.1f %%", 100 * nrow(subset.data.frame(data, data$OE == data$XPO)) / total))
